Module1 task2
htmlacademy-yii/938431-task-force-2 pull request #2
Opened 2021-11-03 16:31 UTC by lula-may

Александр, привет!
Признаюсь, до конца я все-таки не поняла, что требуется от методов, которые описаны в задании: должны они учитывать текущее состояние, или просто выдавать результат в зависимости от переданных параметров.
В общем, если что не так - переделаю))
И еще, не получилось у меня использовать функцию assert для тестирования, про которую написано в задании.
Сделала по простому))

2021-11-04 05:35 UTC, webmayak requested changes
откомментил по коду, но есть ещё замечания по логике методов, отпишусь отдельно

2021-11-04 05:35 UTC, webmayak commented on Task.php
> +    private  $performerId;
поправить кодестайл: убрать двойные пробелы между `private` и именем переменных

2021-11-04 05:35 UTC, webmayak commented on Task.php
> +    const STATUS_NEW = 'new';
для значения всех констант добавить префикс, чтобы было не просто `new`, а `status_new` или `statusNew` (любой вариант, как больше нравится)

2021-11-04 05:35 UTC, webmayak commented on test.php
> +echo "Ожидается статус 'in_progress', получено: " . $task->getNextStatus($task::ACTION_ASSIGN) . "\n";
для передачи констант используем обращение не от переменной `$task` а от имени класса `Task`, так логичнее и общепринято делать именно так:

```suggestion
echo "Ожидается статус 'in_progress', получено: " . $task->getNextStatus(Task::ACTION_ASSIGN) . "\n";
```

2021-11-04 05:35 UTC, webmayak commented on Task.php
> +                $result = $this->currentStatus;
Тут логически неверно, сами себя запутываем: если `$action` неизвестный или некорректный, то надо возвращать null или false, или даже выкидывать исключение. Т.к., повторюсь, возвращение текущего статуса в этом случае это самообман на ровном месте (:

2021-11-05 07:32 UTC, webmayak commented
Финальная проверка. Ещё раз обратимся к ТЗ, чтобы точно понимать от нас требуется:

> Необходимо написать класс, который будет:

- [ ] Определять список из всех доступных действий и статусов;
- [ ] Возвращать имя статуса, в который перейдёт задание после выполнения конкретного действия;
- [ ] Определять список доступных действий в текущем статусе;
- [ ] Хранить текущий статус задания;
- [ ] Хранить ID исполнителя и ID заказчика.

Итого, моё мнение, что по текущему всё сделано как надо, кроме п.3 "Определять список доступных действий в текущем статусе". В нем ключевая фраза "в текущем статусе", поэтому предлагаю:

- [ ] Убираем из метода `getAvailableActions()` параметр `$status` его мы читаем из самого поля объекта
- [ ] Добавляем возможность передать статус объекта в конструкторе класса Task, третьим параметром. Это нужно, чтобы можно было создавать объекты с нужным нам статусом

После выполнения этих моментов считаем задание выполненным ✊

2021-11-05 10:15 UTC, lula-may commented
Привет!
Переделала)
Кроме этого мне редактор предложил заменить switch на match, я согласилась) Как я поняла, это новшество в PHP 8, в PHP 7 вызывает ошибку.
И еще, в комментариях комитов, вылезают какие-то посторонние символы.
Происходит при работе во встроеном в PHPStorm терминале. Это с настройками языка нужно что-то делать?

2021-11-06 02:55 UTC, merged

2021-11-06 03:02 UTC, webmayak commented
Всё супер, молодец!

> заменить switch на match

Да, хорошее решение, изящно и читабельно. Правда у меня самого пока что 7.2 на локальном компе (я использую XAMPP, а не OpenServer и поэтому возможности переключать версию PHP "на лету" у меня нет), но что-нибудь придумаю, подстроюсь =)

> в комментариях коммитов, вылезают какие-то посторонние символы

Да, заметил такое. Вообще я бы рекомендовал попробовать [GitHub Desktop](https://desktop.github.com/). На мой взгляд это самый удобный "клиент", который обеспечивает максимально комфортный процесс и без ущерба профессионализму.